[package]
name = "IDS706_DataEngineering_BarbaraFlores_Miniproject8"
version = "0.1.0"
edition = "2021"

# ...

[dependencies]
rusqlite = "0.25.2"
prettytable = "0.10.0"
reqwest = "0.11"

[[bin]]
name = "main"
path = "src/main.rs"
