[package]
name = "ids706_data_engineering_barbara_flores_project2"
version = "0.1.0"
edition = "2018"

# ...

[dependencies]
rusqlite = "0.25.2"
prettytable = "0.10.0"
reqwest = "0.11"
csv = "1.0"

[[bin]]
name = "main"
path = "src/main.rs"

