name: Rust CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: ./.github/actions/build.yml
      - name: Format Check
        uses: ./.github/actions/format.yml
      - name: Lint
        uses: ./.github/actions/lint.yml
      - name: Test
        uses: ./.github/actions/test.yml
